name: FASTAfurious
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: FASTAfurious test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with: 
          python-version: ${{ matrix.python-version }}
      - name: Install FASTAfurious
        run: |
          pip install pandas>=1.1.5 numpy>=1.19 biopython>=1.79 pytest>=7.1.2 pypandoc>=1.8
          pip install -e .
      - name: Check FASTAfurious installation
        shell: bash -l {0}
        run: fastafurious -h
      - name: Run pytests
        run: pytest tests/
